### ISSUE TITLE
Could this work for other test frameworks?

### ISSUE THREAD

**Issue by maximilianr** [jlubcke/pytest-pycharm#2]
Is this py.test specific? I had a look through the code and don't see anything even mentioning py.test, but I don't have a good understanding. 

We use nosetests and would be keen to have this support in PyCharm.

**Comment by jlubcke** [comment]
Currently it is py.test specific in terms of how it is discovered as a py.test plugin and hooks in to the exception handling (by having a pytest_exception_interact method).
