### ISSUE TITLE
Not working anymore for Pycharm 2016

### ISSUE THREAD

**Issue by pymen** [jlubcke/pytest-pycharm#3]
Looks like problem because of changed variable names, for example
from: thread.additionalInfo
to: thread.additional_info

this is raw fix

`def pytest_exception_interact(node, call, report):

    try:
        import pydevd
        from pydevd import pydevd_tracing
    except ImportError:
        pass
    else:
        exctype, value, traceback = call.excinfo._excinfo
        frames = []
        debugger = pydevd.debugger

        while traceback:
            frames.append(traceback.tb_frame)
            traceback = traceback.tb_next

        thread = threading.current_thread()
        frames_byid = dict([(id(frame), frame) for frame in frames])

        frame = frames[-1]
        exception = (exctype, value, traceback)
        thread.additional_info.pydev_message = 'exception_breakpoint.qname'

        pydevd_tracing.SetTrace(None)  # no tracing from here
        debugger.handle_post_mortem_stop(thread, frame, frames_byid, exception)

    return report`

**Comment by jlubcke** [comment]
Thanks for the fix. I rolled a 0.4.0 release.
