### ISSUE TITLE
Simplify Usage in README

### ISSUE THREAD

**Issue by lancelote** [jlubcke/pytest-pycharm#8]
I believe one can simply run under debugger any `pytest` Run Configuration in PyCharm (e.g. created via right click) and the plugin is going to pause execution on failed assertion. There's no need to e.g. search for `pytest` executable.

Or did I miss something?

**Comment by davethecipo** [comment]
Hi, @jlubcke accepted some time ago my pull request where I added the usage in the README. That was the only way I found at that time to make it work. I can't say if things have changed or I just didn't know enough about Pycharm.

I have just tried again as you suggested and i can confirm that it just works.

**Comment by jlubcke** [comment]
It might be that the plugin is detected automatically by pytest just by being installed in the python environment. The README should probably be simplified. (Feel free to hack away, I'm not doing much with this myself.)
